# Change these first
owner: systemdes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Dandevri
    url: https://dandevri.es

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dandevri.es
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  themeUrl: https://status.dandevri.es/deckard.css
  introTitle: "Open-source uptime monitor and status page, powered entirely by GitHub for my personal website."
  introMessage: This status page is powered by [Upptime](https://github.com/upptime/upptime).
  faviconSvg: https://card.dandevri.es/icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
