# Change these first
owner: systemdes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal Website
    url: https://dandevri.es
  - name: Digital Business Card
    url: https://card.dandevri.es
  - name: URL Shortener
    url: https://dndv.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dandevri.es
  logoUrl: https://avatars.githubusercontent.com/u/38474638?s=200&v=4
  name: Status ▪ Danny de Vries
  theme: night
  introTitle: "Uptime monitor and status page for Danny de Vries."
  introMessage: This status page is powered by [Upptime](https://github.com/upptime/upptime).
  favicon: https://avatars.githubusercontent.com/u/38474638?s=200&v=4
  faviconSvg: https://card.dandevri.es/icon.svg
  css: "nav { display: none; } footer { display: none; } body { display: flex; justify-content: center; align-items: center; height: 97vh; background: black; color: white; }"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
